### ISSUE TITLE
How to set language?

### ISSUE THREAD

**Issue by mootensai** [songluyi/pytesser3#1]
Hi! Thanks for your package!

I've been wondering on how to set language id on this package.. 

Is it supported?
If yes, could you tell me how?

**Comment by songluyi** [comment]
HI!
I wander what means of "language id"
Did u mean it should support reconginize different language?
If so, the answer is probably not. This package can only support English or number OCR translate.

**Comment by mootensai** [comment]
ok then.. thanks!
